
phases:
  install:
    runtime-versions:
      dotnet: 6.0

  pre_build:
    commands:
      - echo pre-build started on `date`
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      
  build:
    commands:
      - echo Building dotnet API...
      - cd aspnet-core/src/SITR.Web.Host
      - echo Executing dotnet restore...
      - dotnet restore
      - echo Executing dotnet publish...
      - dotnet publish -c release -o ../../../docker/build/outputs/Host
  
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker-compose --file=docker-compose-qa.yml push
      - echo Build completed on `date`