# AWS CodeBuild spec to build an Elastic Beanstalk artifact for AWS CodePipeline to deploy

version: 0.2

env:
    variables:
        PROJECT: dev-events-api

phases:   
    pre_build:
        commands:
            - echo Restore started on `date`
            - dotnet restore
      
    build:
        commands:
            - echo Build started on `date`
            - dotnet build -c Release
            - dotnet test -c Release --logger trx --results-directory ./testresults
      
    post_build:
        commands:
            - echo Publish started on `date`
            - dotnet publish --configuration Release --runtime win-x64 -p:PublishReadyToRun=true -p:PublishTrimmed=true --self-contained false
artifacts:
    files:
        - '**/*'
    base-directory: ./build_output
    discard-paths: no